services:
  flarum_db_local:
    image: mariadb:lts
    container_name: my_flarum_db_local_instance
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Reads from .env file
      MYSQL_DATABASE: ${FLARUM_DB_DATABASE}
      MYSQL_USER: ${FLARUM_DB_USERNAME}
      MYSQL_PASSWORD: ${FLARUM_DB_PASSWORD}
    volumes:
      - flarum_db_local_data:/var/lib/mysql
    ports:
      - "33067:3306" # Optional: For direct DB access from your host machine
    networks:
      - flarum_network
  
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8888:8080" # since flarum-web will be on 8080
    environment:
      ADMINER_DEFAULT_SERVER: flarum_db_local
    depends_on:
      - flarum_db_local
    networks:
      - flarum_network

volumes:
  flarum_db_local_data: # Persists Flarum database data

networks:
  flarum_network:
    driver: bridge